{% set name = "icdiff" %}
{% set version = "2.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f79a318891adbf59a45e3a7694f5e1f18c5407065264637072ac8363b759866f

build:
  noarch: python
  number: 1
  entry_points:
    - icdiff=icdiff:start
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  commands:
    - icdiff --help

  imports:
    - icdiff

about:
  home: http://www.jefftk.com/icdiff
  license: Python-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: improved colored diff

extra:
  recipe-maintainers:
    - nicoddemus
