{% set name = "icdiff" %}
{% set version = "2.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 75a3de5c9af35ab45fb0504df59770c514a12c0d2b2c99e5f9c5c2429957e133

build:
  noarch: python
  number: 0
  entry_points:
    - icdiff=icdiff:start
  script: '{{ PYTHON }} -m pip install . --no-deps -vvv '

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  commands:
    - icdiff --help

  imports:
    - icdiff

about:
  home: https://github.com/jeffkaufman/icdiff
  license: Python-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: improved colored diff

extra:
  recipe-maintainers:
    - nicoddemus
